In [33]:
import numpy as np

In [34]:
my1Darray=np.array([1,2,3,4,5])

In [35]:
print(my1Darray)

[1 2 3 4 5]


In [36]:
my2dArray=np.array([[1,2,3,4],[5,6,7,8]])

In [37]:
print(my2dArray)

[[1 2 3 4]
 [5 6 7 8]]


In [38]:
my3dArray=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])

In [39]:
print(my2dArray.data)

In [41]:
print(my3dArray.shape)

(2, 2, 4)


In [42]:
print(my3dArray.strides)

(32, 16, 4)


In [44]:
print(my3dArray.dtype)

int32


In [46]:
ones=np.ones((1,4))
print(ones)

[[1. 1. 1. 1.]]


In [47]:
zeros=np.zeros((2,3,4))
print(zeros)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [50]:
empty=np.empty((2,3))
print(empty)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [1.89142822e-307 2.67020407e-306 2.42092166e-322]]


In [52]:
full=np.full((1,3),7)
print(full)

[[7 7 7]]


In [54]:
arr=np.arange(10,25,5)
print(arr)

[10 15 20]


In [56]:
arr=np.array([1,2,3,4,5])
file=open("arr","wb")
np.save(file,arr)
file.close
file=open("arr","rb")
arr1=np.load(file)
print(arr1)

[1 2 3 4 5]


In [58]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
print(np.add(arr1,arr2))
print(np.subtract(arr1,arr2))
print(np.multiply(arr1,arr2))
print(np.divide(arr1,arr2))

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
